# Generated by Django 2.2.1 on 2019-08-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190829_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actioned',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('None', 'none'), ('Work', 'work'), ('Personal', 'personal'), ('Study', 'study'), ('Research', 'research')], default='none', max_length=100, verbose_name='Choose Category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=100, verbose_name=' '),
        ),
    ]
