# Generated by Django 2.2.1 on 2019-08-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190829_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actioned',
            field=models.BooleanField(default=False),
        ),
    ]
