# Generated by Django 2.2.1 on 2019-09-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20190829_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='actioned',
        ),
    ]
