# Generated by Django 2.2.1 on 2019-09-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_task_actioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actioned',
            field=models.BooleanField(default=False),
        ),
    ]
